---
title: "divvy_project"
author: "Imogen Meers, Sarah Deussing, Sarah Cernugel"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
divvy <- read.csv("divvy data.csv")
head(divvy)
```
```{r}
library(dplyr)
library(readr)
library(purrr)
library(stringr)
library(tibble)
library(magick)
library(aws.s3)
library(tidyr)
```

```{r Reading from S3 bucket}
bucket_exists("s3://divvy-tripdata/") #check bucket exists

data <- get_bucket_df(
  bucket = "s3://divvy-tripdata/", 
  region = "us-east-1", 
  max = 20000
) %>% 
  as_tibble() #find contents of bucket

keys <- data[1:54,]$Key #get zip files that we want

save_object(object = keys[[1]], bucket = "divvy-tripdata",region = "us-east-1", file = temp) 
s3read_using(FUN = save_object, object = keys[[1]], bucket = "divvy-tripdata", region = "us-east-1", file = temp)

download_and_unzip <- function(key) { 
  temp <- tempfile() 
  save_object(object = key, bucket = "divvy-tripdata",region = "us-east-1", file = temp) 
  unzipped_files <- unzip(temp, exdir = tempdir()) 
  print(paste("File ", key, " unzipped"))
  return(read.csv(unzipped_files[1]))
} # Function to unzip each file into a temp file 

# Apply function to each key in your data frame 
result_list <- lapply(keys, download_and_unzip)

# Combine into a single data frame 
result_df <- do.call(rbind, result_list)


# save_object(
#   object = "202004-divvy-tripdata.zip",
#   bucket = "s3://divvy-tripdata/", 
#   region = "us-east-1",
#   file = "202004-divvy-tripdata.zip"
# )

#Should save as a RData file to prevent having to run this every time
```


```{r Reading from S3 bucket}
load("InitRData.RDataTmp")
```

```{r}
summary(result_df)
```
```{r}
library(dplyr)
head(result_df)
unique(result_df$rideable_type)
summary(as.factor(result_df$rideable_type))

scooter <- result_df %>% filter(rideable_type == "electric_scooter")
summary(scooter)
docked_bike <- result_df %>% filter(rideable_type == "docked_bike")
```


```{r}
summary(classic_bike)
```

```{r}
library(ggmap)
register_stadiamaps("9e07144d-cdab-48f9-a35d-298e1bbece2e")

# Define the bounding box for Chicago
bbox <- c(left = -87.9400, bottom = 41.6445, right = -87.5240, top = 42.0230)

# Get the map
chi_map <- get_stadiamap(bbox = bbox, zoom = 12, maptype = "stamen_toner")


# Plot the map
scooter_map <- ggmap(chi_map) +
  geom_point(data = scooter, aes(x = start_lng, y = start_lat, alpha = 0.05, color = "red")) +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.x = element_blank(),
    axis.ticks.y = element_blank(),
  ) + 
  labs(
    title = "Scooter Map"
  )+
  guides(alpha = "none")

scooter_map
```

```{r}
# Plot the map
bike_map <- ggmap(chi_map) +
  geom_point(data = docked_bike, aes(x = start_lng, y = start_lat, alpha = 0.05, color = "blue")) +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.x = element_blank(),
    axis.ticks.y = element_blank(),
  ) + 
  labs(
    title = "Bike Map"
  )+
  guides(alpha = "none")

bike_map
```

## NBA Schedule
```{r cars}
#install.packages("hoopR")
library(hoopR)
nba_19 <- nba_schedule(league_id = "00", season = 2019)
nba_20 <- nba_schedule(league_id = "00", season = 2020)
nba_21 <- nba_schedule(league_id = "00", season = 2021)
nba_22 <- nba_schedule(league_id = "00", season = 2022)
nba_23 <- nba_schedule(league_id = "00", season = 2023)
nba_24 <- nba_schedule(league_id = "00", season = 2024)

#nba <- full_join(nba_20, full_join(nba_21, full_join(nba_22, full_join(nba_23, nba_24))))
nba <- rbind(nba_19,nba_20, nba_21, nba_22, nba_23, nba_24)

nba <- filter(nba, arena_name == "United Center", game_status == "3")
nba %>% arrange(desc(game_date))
summary(nba)
set_dates <- unique(nba$game_date)
```

## MLB Schedule
```{r}
#install.packages("baseballr")
library(baseballr)

mlb_20 <- mlb_schedule(season = 2020, level_ids = "1")
mlb_21 <- mlb_schedule(season = 2021, level_ids = "1")
mlb_22 <- mlb_schedule(season = 2022, level_ids = "1")
mlb_23 <- mlb_schedule(season = 2023, level_ids = "1")
mlb_24 <- mlb_schedule(season = 2024, level_ids = "1")

mlb <- rbind(mlb_20, mlb_21, mlb_22, mlb_23, mlb_24)
#mlb <- full_join(mlb_20, full_join(mlb_21, full_join(mlb_22, full_join(mlb_23, mlb_24))))
mlb <- mlb %>% filter(venue_name == "Wrigley Field" | venue_name == "Guaranteed Rate Field") %>% mutate(date = as.Date(date))
set_dates <-  unique(c(set_dates, unique(mlb$date))) 
```

```{r}
head(result_df)
x <- head(result_df, 50) %>% mutate(start_date = as.Date(started_at))

inner_join(x, mlb, by = c("start_date" = "date"))
```


## NFL Schedule
```{r}
#install.packages("nflfastR")
library(nflfastR)
nfl <- nflreadr::load_schedules()
nfl$gameday <- as.Date(nfl$gameday)
nfl <- nfl %>%
  filter(gameday >= as.Date('2020-01-01') & gameday <= as.Date('2024-12-31') & stadium == "Soldier Field")
set_dates <-  unique(c(set_dates, unique(nfl$gameday))) 

```

## NHL Schedule
```{r}
#install.packages('fastRhockey')
library(fastRhockey)
nhl20 <- load_nhl_schedule(2020)
nhl21 <- load_nhl_schedule(2021)
nhl22 <- load_nhl_schedule(2022)
nhl23 <- load_nhl_schedule(2023)
nhl24 <- load_nhl_schedule(2024)

nhl <- rbind(nhl20, nhl21, nhl22, nhl23, nhl24, fill=TRUE)
nhl <- nhl %>% filter(venue_name == "United Center") %>% mutate(game_date = as.Date(game_date))
set_dates <-  unique(c(set_dates, unique(nhl$game_date))) 



```

